Style/Documentation:
  Enabled: false
  
Layout/LineLength:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false
  
Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/BlockLength:
  Enabled: false
  
Lint/EmptyFile:
  Enabled: false